import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Banner from "@/app/components/Banner";
import {Container} from "@/app/components/Container";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <main className="min-h-screen">
              <Banner />
              <Container>
                  {children}
              </Container>
          </main>
      </body>
    </html>
  )
}
